# Generated by Django 5.1.3 on 2024-11-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened', models.BooleanField()),
                ('id_number', models.BooleanField(null=True)),
                ('credit_card', models.BooleanField(null=True)),
                ('address', models.BooleanField(null=True)),
                ('phone_number', models.BooleanField()),
                ('email', models.BooleanField(null=True)),
                ('bank_account', models.BooleanField(null=True)),
                ('password', models.BooleanField(null=True)),
                ('social_media', models.BooleanField(null=True)),
                ('medical_info', models.BooleanField(null=True)),
                ('personal_photos', models.BooleanField(null=True)),
                ('type', models.CharField(choices=[('PRZ', 'Prize'), ('PHI', 'Phishing'), ('TSP', 'Tech Support Scam'), ('ROM', 'Romance Scam'), ('INV', 'Investment Fraud'), ('CHA', 'Fake Charity'), ('LOT', 'Lottery Scam'), ('IMP', 'Imposter (e.g., posing as a family member or friend)'), ('JOB', 'Fake Job Offer'), ('DEL', 'Fake Delivery Notice'), ('GOV', 'Fake Government Request')], max_length=3)),
            ],
        ),
    ]
