# Generated by Django 5.1.3 on 2024-11-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ankesy_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='parent_email',
            field=models.EmailField(default='lgurjidze@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
