# Generated by Django 5.1.3 on 2024-11-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ankesy_api', '0002_report_parent_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('PRZ', 'Prize Scam'), ('PHI', 'Phishing'), ('TSP', 'Tech Support Scam'), ('ROM', 'Romance Scam'), ('INV', 'Investment Fraud'), ('CHA', 'Fake Charity'), ('LOT', 'Lottery Scam'), ('IMP', 'Imposter (e.g., posing as a family member or friend)'), ('JOB', 'Fake Job Offer'), ('DEL', 'Fake Delivery Notice'), ('GOV', 'Fake Government Request')], max_length=3),
        ),
    ]
