name: Ankesy CI/CD Pipeline

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ] 

jobs:
  deploy:
    name: deploy to digitalocean
    runs-on: ubuntu-latest
    # needs: build
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    steps: 
      - name: deploy to digitalocean
        uses: appleboy/ssh-action@v1.0.3
        with:
           host: ${{ secrets.SSH_HOST}}
           username: ${{ secrets.SSH_USERNAME}}
           key: ${{ secrets.SSH_PRIVATE_KEY}}

           script: |
              cd Ankesy
              echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" > .env
              echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env

              

              docker compose down
              git pull origin master
              docker compose up --build --detach



    